name: bank-platform

services:
  dev-db:
    image: postgres:17.6
    container_name: bank-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: bank-platform
    networks:
      - networkName

  backend:
    build:
      context: ./backend
    container_name: bank-backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:123@dev-db:5432/bank-platform?schema=public
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production-12345678
      - JWT_EXPIRES_IN=7d
      - NODE_ENV=development
      - CORS_ORIGIN=http://localhost:5173
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - MAILTRAP_HOST=sandbox.smtp.mailtrap.io
      - MAILTRAP_PORT=2525
      - MAILTRAP_USER=b01af44c3bc7b3
      - MAILTRAP_PASS=68eacdfab1bfb5
    depends_on:
      - dev-db
    networks:
      - networkName
    command: >
      sh -c "npm rebuild esbuild
      && npx prisma generate
      && npx prisma migrate deploy
      && npm run dev"

  frontend:
    build:
      context: ./frontend
      target: build
    container_name: bank-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - networkName
    command: >
      sh -c "npm rebuild rollup vite esbuild
      && npm run dev -- --host"

networks:
  networkName:
