# Utiliser une image Node.js officielle (version 20 ou 22)
FROM node:22-alpine

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers de dépendances en premier (pour optimiser le cache Docker)
COPY package.json package-lock.json* ./

# Installer les dépendances
RUN npm install

# Copier le reste du code
COPY . .

# Exposer le port de ton app
EXPOSE 5001

# La commande de démarrage sera gérée par le docker-compose
CMD ["npm", "run", "dev"]